#!/usr/bin/env bash

shell::rcfile() {
  local shell_name="$1"
  shift

  local debug=""
  for arg in "$@"; do
    case "$arg" in
      --debug)
        debug="$arg"
        ;;
      *)
        stdlib_error_fatal "unsupported option $arg"
        ;;
    esac
  done

  local -a buffer=()

  # Add the comment banner
  buffer+=("# AUTOGENERATED MESSAGE")
  buffer+=("")

  # $SHELL seems hit or miss, so just make it a thing
  buffer+=("export SHELL=\"$shell_name\"")
  buffer+=("")

  # Add the devmachine config vars
  buffer+=("export DEVMACHINE_PATH=\"$DEVMACHINE_PATH\"")
  buffer+=("export DEVMACHINE_CACHE_PATH=\"$DEVMACHINE_CACHE_PATH\"")
  buffer+=("export DEVFILES_PATH=\"$DEVFILES_PATH\"")
  buffer+=("PATH=\"\$PATH:\$DEVMACHINE_PATH/bin\"")
  buffer+=("")

  # Loop through each devfile, check if it's installed, and add it to
  # our running devfiles buffer
  for devfile in $(devfile::list --filter installed); do
    printf -v devfile_baner '####### %s #######' "${devfile}"
    buffer+=("$devfile_baner")

    buffer+=("$(devmachine "$devfile" shellenv "$shell_name")")
  done

  buffer+=("devmachine $shell_name motd")

  stdlib_array_join --delim $'\n' "${buffer[@]}"
}
